// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_tCyBfyk9-pbxYqKnSlE28pa2Yd9ivPg',
    appId: '1:385697279961:web:8b18f30028c6fb9604b3c8',
    messagingSenderId: '385697279961',
    projectId: 'cotidyfitapp-bbdd',
    authDomain: 'cotidyfitapp-bbdd.firebaseapp.com',
    storageBucket: 'cotidyfitapp-bbdd.firebasestorage.app',
    measurementId: 'G-3HNK2RZP48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdwnpUZsPemQzsK68Kg3MAVFw42ipOqfE',
    appId: '1:385697279961:android:a10814b723b7060404b3c8',
    messagingSenderId: '385697279961',
    projectId: 'cotidyfitapp-bbdd',
    storageBucket: 'cotidyfitapp-bbdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6YNwRgDO3OK-Os2I6N_TeWw68pJayxa8',
    appId: '1:385697279961:ios:02dc3b0528058ded04b3c8',
    messagingSenderId: '385697279961',
    projectId: 'cotidyfitapp-bbdd',
    storageBucket: 'cotidyfitapp-bbdd.firebasestorage.app',
    iosClientId: '385697279961-36uod46r5i4ne4ue20rcs2ha724hvnu9.apps.googleusercontent.com',
    iosBundleId: 'com.example.cotidyfitapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6YNwRgDO3OK-Os2I6N_TeWw68pJayxa8',
    appId: '1:385697279961:ios:02dc3b0528058ded04b3c8',
    messagingSenderId: '385697279961',
    projectId: 'cotidyfitapp-bbdd',
    storageBucket: 'cotidyfitapp-bbdd.firebasestorage.app',
    iosClientId: '385697279961-36uod46r5i4ne4ue20rcs2ha724hvnu9.apps.googleusercontent.com',
    iosBundleId: 'com.example.cotidyfitapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_tCyBfyk9-pbxYqKnSlE28pa2Yd9ivPg',
    appId: '1:385697279961:web:410ed1187031c39d04b3c8',
    messagingSenderId: '385697279961',
    projectId: 'cotidyfitapp-bbdd',
    authDomain: 'cotidyfitapp-bbdd.firebaseapp.com',
    storageBucket: 'cotidyfitapp-bbdd.firebasestorage.app',
    measurementId: 'G-ECBQG3X6BZ',
  );

}